#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
# Leng-Lang v0.1

import os
import time
from sys import *
from dosya_ac import *
from leng2 import *
from parser import *

semboller = ()

def calis_shell():
        try:
                print("LengLang v0.1 \n")
                while True:
                        veri = raw_input("<?>: ") + "\n<EOF>"
                        open(".shell_data","w").write(veri)
                        tks = leng2(veri)
                        parser.parser(tks,0)
        except ValueError:
                                print("HATA!")
                                exit()
def calis_dosya():
        veri = dosya_ac(argv[1])
        tks = leng2(veri)
        parser(tks,0)

if len(argv) == 2:
        calis_dosya()
        
elif len(argv) == 1:
        calis_shell()
else:
        print("HATA: ASIRI YUKLEME")
